# Generated by Django 2.0.2 on 2018-05-22 18:43

from django.db import migrations, models
import django.utils.timezone
import utils.images


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picsmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='picsmodel',
            name='img',
            field=models.ImageField(default='media/pics/default.png', storage=utils.images.ImageStorage(), upload_to='media/pics/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='picsmodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
